version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    image: strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_HOST: "store"
      DATABASE_PORT: 5432
      DATABASE_NAME: "storeSandboxDB"
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      APP_KEYS: "68Zgyzc6b51rjaUyFJYO4g==,3DwZKkLwyTH/SvAdKC+QIQ==,Vu/W8epSV3HA51BF8ngRUw==,uFL+iOrPT+cO4NgHLQgF0Q=="
      API_TOKEN_SALT: "sLH3abgEV37vPB+2CivdlQ=="
      ADMIN_JWT_SECRET: "CBVLkIjNjyMSJFeFVrDi2g=="
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - cms
    depends_on:
      - store

  store:
    container_name: store
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'storeSandboxDB'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - cms

volumes:
  postgres:


networks:
  cms:
    name: CMS
    driver: bridge
