version: '3'
services:
  sandbox-cms-api:
    container_name: sandbox-cms-api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_HOST: "sandbox-cms-store"
      DATABASE_PORT: 5432
      DATABASE_NAME: "storeSandboxDB"
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      APP_KEYS: "68Zgyzc6b51rjaUyFJYO4g==,3DwZKkLwyTH/SvAdKC+QIQ==,Vu/W8epSV3HA51BF8ngRUw==,uFL+iOrPT+cO4NgHLQgF0Q=="
      API_TOKEN_SALT: "sLH3abgEV37vPB+2CivdlQ=="
      JWT_SECRET: "C2tCDpH9aUDiqdP1iWaVaA=="
      ADMIN_JWT_SECRET: "CBVLkIjNjyMSJFeFVrDi2g=="
      STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE: "pt-BR"
      STRAPI_TELEMETRY_DISABLED: true
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./package.json:/package.json
      - ./yarn.lock:/yarn.lock
      - ./public/uploads:/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - sandbox-cms-network
    depends_on:
      - sandbox-cms-store

  sandbox-cms-store:
    container_name: sandbox-cms-store
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'storeSandboxDB'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - sandbox-cms-network

volumes:
  postgres:


networks:
  sandbox-cms-network:
    name: sandbox-cms
    driver: bridge
