version: '3'
services:
  cms-api:
    container_name: cms-api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    restart: unless-stopped
    environment:
      DATABASE_HOST: "cms-store"
      DATABASE_PORT: 5432
      DATABASE_NAME: "storeSandboxDB"
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      APP_KEYS: "68Zgyzc6b51rjaUyFJYO4g==,3DwZKkLwyTH/SvAdKC+QIQ==,Vu/W8epSV3HA51BF8ngRUw==,uFL+iOrPT+cO4NgHLQgF0Q=="
      API_TOKEN_SALT: "sLH3abgEV37vPB+2CivdlQ=="
      ADMIN_JWT_SECRET: "CBVLkIjNjyMSJFeFVrDi2g=="
    ports:
      - '1337:1337'
    networks:
      - cms-network
    depends_on:
      - cms-store

  cms-store:
    container_name: cms-store
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'storeSandboxDB'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - cms-network

volumes:
  postgres:


networks:
  cms-network:
    name: CMS
    driver: bridge
