name: Build

on:
  - push

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: '[Install] | Install Dependencies'
        run: yarn install --frozen-lockfile
        shell: bash

      - name: '[TEST] | Lint Check'
        run: yarn lint:check
        shell: bash

      - name: '[BUILD] | Build'
        run: yarn build
        shell: bash
