name: Build CMS Stack

on:
  - push
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "[BUILD] | Build Webpack"
        run: yarn build
        shell: bash
